# Load data

In [3]:
import pandas as pd
df = pd.read_csv("adjprice.csv")
df

,Date,0111145D US Equity,0202445Q US Equity,0203524D US Equity,0226226D US Equity,0376152D US Equity,0440296D US Equity,0544749D US Equity,0574018D US Equity,0598884D US Equity,...,YNR US Equity,YRCW US Equity,YUM US Equity,YUMC US Equity,ZBH US Equity,ZETHQ US Equity,ZION US Equity,ZRN US Equity,ZTS US Equity,ZTS-W US Equity
0,19930907,13.2719,13.6829,8.4429,8.1042,11.000,57.3245,17.8887,6.8315,28.1246,...,NaN,144439.5121,NaN,NaN,NaN,6.875,7.1675,30.7970,NaN,NaN
1,19930908,13.3263,13.5315,8.2147,7.9590,11.000,57.2096,17.8064,6.8315,27.5051,...,NaN,143691.1208,NaN,NaN,NaN,6.750,6.9766,30.0188,NaN,NaN
2,19930909,13.7070,13.3800,8.7852,8.0627,11.125,59.1625,17.6831,6.8315,27.7529,...,NaN,143691.1208,NaN,NaN,NaN,6.625,6.9554,30.0188,NaN,NaN
3,19930910,13.3807,13.4810,9.4127,8.0368,11.125,59.6220,17.6420,6.8773,27.5051,...,NaN,145187.9033,NaN,NaN,NaN,6.750,7.2099,29.6852,NaN,NaN
4,19930911,13.3807,13.4810,9.4127,8.0368,11.125,59.6220,17.6420,6.8773,27.5051,...,NaN,145187.9033,NaN,NaN,NaN,6.750,7.2099,29.6852,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9454,20190727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.3500,114.02,45.31,134.50,NaN,45.1600,NaN,115.11,NaN
9455,20190728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.3500,114.02,45.31,134.50,NaN,45.1600,NaN,115.11,NaN
9456,20190729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.1800,114.10,45.43,134.53,NaN,44.6500,NaN,115.55,NaN
9457,20190730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.1800,113.24,44.00,136.67,NaN,45.4800,NaN,115.79,NaN
9458,20190731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.1800,113.24,44.00,136.67,NaN,45.4800,NaN,115.79,NaN

# Keep stocks with 90% coverage

In [4]:
coverage = df.notna().mean()
df = df.loc[:, coverage >= 0.9]
df

,Date,1436513D US Equity,AA US Equity,AAPL US Equity,ABC US Equity,ABMD US Equity,ABT US Equity,ABX US Equity,ADBE US Equity,ADI US Equity,...,WY US Equity,X US Equity,XEL US Equity,XL US Equity,XLNX US Equity,XOM US Equity,XRAY US Equity,XRX US Equity,YRCW US Equity,ZION US Equity
0,19930907,3.0147,13.6285,0.8044,NaN,3.750,3.2659,16.9898,2.3712,2.9608,...,6.7803,20.5434,6.9696,12.3149,2.5342,8.0198,5.3036,20.5503,144439.5121,7.1675
1,19930908,2.9691,13.3718,0.8197,NaN,4.375,3.2037,17.0863,2.4320,2.9025,...,6.6519,20.3829,6.9696,12.2506,2.4735,8.0815,5.1244,20.5503,143691.1208,6.9766
2,19930909,3.0278,13.4652,0.7967,NaN,4.375,3.2659,17.1828,2.3104,3.0046,...,6.5878,20.4632,6.9326,12.2506,2.5797,8.0044,5.1244,20.3040,143691.1208,6.9554
3,19930910,3.0278,13.3952,0.8044,NaN,4.125,3.2659,16.6036,2.3712,3.1067,...,6.6947,20.7039,7.0065,12.2506,2.7087,8.0969,5.3036,20.4096,145187.9033,7.2099
4,19930911,3.0278,13.3952,0.8044,NaN,4.125,3.2659,16.6036,2.3712,3.1067,...,6.6947,20.7039,7.0065,12.2506,2.7087,8.0969,5.3036,20.4096,145187.9033,7.2099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9454,20190727,NaN,23.1300,207.7400,86.12,272.660,87.7500,NaN,311.2700,121.8000,...,26.2100,15.1900,60.5100,57.5900,120.7700,74.8100,56.0200,34.4300,3.3500,45.1600
9455,20190728,NaN,23.1300,207.7400,86.12,272.660,87.7500,NaN,311.2700,121.8000,...,26.2100,15.1900,60.5100,57.5900,120.7700,74.8100,56.0200,34.4300,3.3500,45.1600
9456,20190729,NaN,23.1200,209.6800,87.23,275.930,88.5500,NaN,307.2200,121.2100,...,25.8400,15.2700,60.9800,57.5900,120.5500,75.3400,56.3700,33.9400,3.1800,44.6500
9457,20190730,NaN,23.0400,208.7800,88.72,279.230,88.3100,NaN,303.6400,120.9600,...,26.0900,15.7100,60.5900,57.5900,119.5100,75.3500,56.6700,32.7800,3.1800,45.4800
9458,20190731,NaN,23.0400,208.7800,88.72,279.230,88.3100,NaN,303.6400,120.9600,...,26.0900,15.7100,60.5900,57.5900,119.5100,75.3500,56.6700,32.7800,3.1800,45.4800

# Drop any rows with N/A values

In [5]:
df_clean = df.dropna()
df_clean

,Date,1436513D US Equity,AA US Equity,AAPL US Equity,ABC US Equity,ABMD US Equity,ABT US Equity,ABX US Equity,ADBE US Equity,ADI US Equity,...,WY US Equity,X US Equity,XEL US Equity,XL US Equity,XLNX US Equity,XOM US Equity,XRAY US Equity,XRX US Equity,YRCW US Equity,ZION US Equity
904,19960228,3.9666,21.4810,0.8753,2.9793,6.063,5.4616,23.8016,4.1685,7.2854,...,8.0538,23.0299,8.5667,19.6972,8.2626,10.7800,5.8269,40.5005,72042.1892,13.4914
905,19960229,4.0085,22.3658,0.8674,2.9793,6.063,5.5111,23.6065,4.1377,7.0556,...,7.8455,22.5986,8.4594,19.2825,7.0334,10.9522,5.7542,39.3304,71637.4578,13.4232
906,19960301,3.9037,22.5133,0.8477,2.8766,6.438,5.5771,23.5089,4.0296,6.5634,...,7.7761,22.6849,8.6096,19.3517,5.6905,10.9867,5.6453,39.1417,72042.1892,13.5142
907,19960302,3.9037,22.5133,0.8477,2.8766,6.438,5.5771,23.5089,4.0296,6.5634,...,7.7761,22.6849,8.6096,19.3517,5.6905,10.9867,5.6453,39.1417,72042.1892,13.5142
908,19960303,3.9037,22.5133,0.8477,2.8766,6.438,5.5771,23.5089,4.0296,6.5634,...,7.7761,22.6849,8.6096,19.3517,5.6905,10.9867,5.6453,39.1417,72042.1892,13.5142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8413,20160919,45.4500,20.9622,109.5665,80.0464,125.100,39.7491,16.9158,99.6800,59.8806,...,27.9673,16.5371,39.0638,32.4004,51.0060,76.8618,58.8778,24.0173,11.7500,28.9620
8414,20160920,45.4500,21.1414,109.5569,78.9119,125.100,39.6538,16.9256,100.6200,59.7655,...,27.8095,16.3699,38.9138,32.4390,50.4720,75.6790,58.7299,23.9198,11.6800,28.9329
8415,20160921,45.4500,21.6565,109.5376,79.8156,126.900,39.9780,18.3918,107.7800,60.6859,...,28.1623,17.6094,39.8792,33.1146,50.7771,76.3758,59.0454,24.2367,11.9000,29.0492
8416,20160922,45.4500,21.9028,110.5698,80.3636,126.370,40.2641,18.2344,107.9200,61.0502,...,29.7774,17.9046,40.2072,33.4813,50.9583,76.5959,59.1637,24.4074,12.2600,29.3301
8417,20160923,45.4500,21.8581,108.7272,80.1137,123.530,40.2355,17.8211,107.4700,60.6188,...,29.8702,18.6424,40.3666,33.0277,50.6531,76.5134,58.5229,24.1880,12.3500,29.6497

# Remove duplicated rows (weekends and public holidays) and non-publicly traded entities (numerical tickers)

In [27]:
df_cleaned = df_clean[~df_clean.iloc[:, 1:].duplicated()]
df_cleaned = df_cleaned.drop(df.columns[1], axis=1)
df_cleaned

,Date,AA US Equity,AAPL US Equity,ABC US Equity,ABMD US Equity,ABT US Equity,ABX US Equity,ADBE US Equity,ADI US Equity,ADM US Equity,...,WY US Equity,X US Equity,XEL US Equity,XL US Equity,XLNX US Equity,XOM US Equity,XRAY US Equity,XRX US Equity,YRCW US Equity,ZION US Equity
904,19960228,21.4810,0.8753,2.9793,6.063,5.4616,23.8016,4.1685,7.2854,9.5428,...,8.0538,23.0299,8.5667,19.6972,8.2626,10.7800,5.8269,40.5005,72042.1892,13.4914
905,19960229,22.3658,0.8674,2.9793,6.063,5.5111,23.6065,4.1377,7.0556,9.3605,...,7.8455,22.5986,8.4594,19.2825,7.0334,10.9522,5.7542,39.3304,71637.4578,13.4232
906,19960301,22.5133,0.8477,2.8766,6.438,5.5771,23.5089,4.0296,6.5634,9.4212,...,7.7761,22.6849,8.6096,19.3517,5.6905,10.9867,5.6453,39.1417,72042.1892,13.5142
909,19960304,22.8574,0.8280,2.9279,6.063,5.7916,22.5335,3.9987,6.4321,9.4212,...,8.1464,23.1162,8.6955,19.5936,5.2352,10.9350,5.7542,38.9530,71232.7264,13.5369
910,19960305,22.8082,0.8398,3.0050,6.063,5.7091,22.8261,4.0450,6.8259,9.2997,...,8.0538,23.0299,8.7170,19.6281,5.7588,11.1417,5.7542,39.7834,70423.2636,13.6052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8413,20160919,20.9622,109.5665,80.0464,125.100,39.7491,16.9158,99.6800,59.8806,39.4369,...,27.9673,16.5371,39.0638,32.4004,51.0060,76.8618,58.8778,24.0173,11.7500,28.9620
8414,20160920,21.1414,109.5569,78.9119,125.100,39.6538,16.9256,100.6200,59.7655,39.4089,...,27.8095,16.3699,38.9138,32.4390,50.4720,75.6790,58.7299,23.9198,11.6800,28.9329
8415,20160921,21.6565,109.5376,79.8156,126.900,39.9780,18.3918,107.7800,60.6859,40.0260,...,28.1623,17.6094,39.8792,33.1146,50.7771,76.3758,59.0454,24.2367,11.9000,29.0492
8416,20160922,21.9028,110.5698,80.3636,126.370,40.2641,18.2344,107.9200,61.0502,40.1849,...,29.7774,17.9046,40.2072,33.4813,50.9583,76.5959,59.1637,24.4074,12.2600,29.3301
8417,20160923,21.8581,108.7272,80.1137,123.530,40.2355,17.8211,107.4700,60.6188,39.7081,...,29.8702,18.6424,40.3666,33.0277,50.6531,76.5134,58.5229,24.1880,12.3500,29.6497

# Get tickers

In [9]:
tickers = []
for col in df_cleaned.columns[2:]:
    tickers.append(col.split()[0])

ticker_df = pd.DataFrame({"Ticker": tickers})
ticker_df

    Ticker
0       AA
1     AAPL
2      ABC
3     ABMD
4      ABT
..     ...
451    XOM
452   XRAY
453    XRX
454   YRCW
455   ZION

[456 rows x 1 columns]

# Load dataset containing tickers and their corresponding sectors

In [12]:
sectors = pd.read_csv("SP500.csv")
sector_df = sectors.rename(columns={"Symbol": "Ticker"})
sector_df

    Ticker                    Name                  Sector
0      MMM              3M Company             Industrials
1      AOS         A.O. Smith Corp             Industrials
2      ABT     Abbott Laboratories             Health Care
3     ABBV             AbbVie Inc.             Health Care
4      ACN           Accenture plc  Information Technology
..     ...                     ...                     ...
500    XYL              Xylem Inc.             Industrials
501    YUM         Yum! Brands Inc  Consumer Discretionary
502    ZBH  Zimmer Biomet Holdings             Health Care
503   ZION           Zions Bancorp              Financials
504    ZTS                  Zoetis             Health Care

[505 rows x 3 columns]

# Merge ticker-sector dataframe with tickers dataset

In [14]:
ticker_df = ticker_df.merge(sector_df, on="Ticker", how="left")
ticker_df

    Ticker                    Name                  Sector
0       AA                     NaN                     NaN
1     AAPL              Apple Inc.  Information Technology
2      ABC  AmerisourceBergen Corp             Health Care
3     ABMD                     NaN                     NaN
4      ABT     Abbott Laboratories             Health Care
..     ...                     ...                     ...
451    XOM       Exxon Mobil Corp.                  Energy
452   XRAY         Dentsply Sirona             Health Care
453    XRX             Xerox Corp.  Information Technology
454   YRCW                     NaN                     NaN
455   ZION           Zions Bancorp              Financials

[456 rows x 3 columns]

# Number of unclassified tickers

In [15]:
ticker_df["Name"].isna().sum()

114

# Fill N/A sectors with "unknown"

In [23]:
ticker_df["Sector"] = ticker_df["Sector"].fillna("Unknown")
ticker_df

    Ticker                    Name                  Sector
0       AA                     NaN                 Unknown
1     AAPL              Apple Inc.  Information Technology
2      ABC  AmerisourceBergen Corp             Health Care
3     ABMD                     NaN                 Unknown
4      ABT     Abbott Laboratories             Health Care
..     ...                     ...                     ...
451    XOM       Exxon Mobil Corp.                  Energy
452   XRAY         Dentsply Sirona             Health Care
453    XRX             Xerox Corp.  Information Technology
454   YRCW                     NaN                 Unknown
455   ZION           Zions Bancorp              Financials

[456 rows x 3 columns]

# Convert raw prices into returns

In [29]:
returns = df_cleaned.iloc[:, 1:].pct_change().dropna()
returns

,AA US Equity,AAPL US Equity,ABC US Equity,ABMD US Equity,ABT US Equity,ABX US Equity,ADBE US Equity,ADI US Equity,ADM US Equity,ADP US Equity,...,WY US Equity,X US Equity,XEL US Equity,XL US Equity,XLNX US Equity,XOM US Equity,XRAY US Equity,XRX US Equity,YRCW US Equity,ZION US Equity
905,0.041190,-0.009025,0.000000,0.000000,0.009063,-0.008197,-0.007389,-0.031543,-0.019103,-0.034269,...,-0.025864,-0.018728,-0.012525,-0.021054,-0.148767,0.015974,-0.012477,-0.028891,-0.005618,-0.005055
906,0.006595,-0.022712,-0.034471,0.061851,0.011976,-0.004134,-0.026126,-0.069760,0.006485,0.012896,...,-0.008846,0.003819,0.017755,0.003589,-0.190932,0.003150,-0.018925,-0.004798,0.005650,0.006779
909,0.015284,-0.023239,0.017834,-0.058248,0.038461,-0.041491,-0.007668,-0.020005,0.000000,-0.012732,...,0.047620,0.019013,0.009977,0.012500,-0.080011,-0.004706,0.019290,-0.004821,-0.011236,0.001680
910,-0.002152,0.014251,0.026333,0.000000,-0.014245,0.012985,0.011579,0.061224,-0.012896,0.003224,...,-0.011367,-0.003733,0.002473,0.001761,0.100015,0.018903,0.000000,0.021318,-0.011364,0.005045
911,0.006467,-0.016432,0.008552,0.000000,-0.002890,0.000000,-0.030532,-0.028846,0.006538,-0.003214,...,-0.002868,0.026218,0.002466,0.010561,0.003942,0.016999,0.006326,-0.015182,0.000000,-0.006689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8413,-0.008476,-0.011661,-0.010106,0.001361,-0.004538,-0.008650,0.007581,0.006608,0.003568,-0.002189,...,0.007355,0.056569,0.011651,0.003590,0.002437,-0.002379,0.001509,0.005101,0.008584,0.000000
8414,0.008549,-0.000088,-0.014173,0.000000,-0.002398,0.000579,0.009430,-0.001922,-0.000710,0.014210,...,-0.005642,-0.010111,-0.003840,0.001191,-0.010469,-0.015389,-0.002512,-0.004060,-0.005957,-0.001005
8415,0.024365,-0.000176,0.011452,0.014388,0.008176,0.086626,0.071159,0.015400,0.015659,0.012416,...,0.012686,0.075718,0.024809,0.020827,0.006045,0.009207,0.005372,0.013248,0.018836,0.004020
8416,0.011373,0.009423,0.006866,-0.004177,0.007156,-0.008558,0.001299,0.006003,0.003970,0.006525,...,0.057350,0.016764,0.008225,0.011074,0.003569,0.002882,0.002004,0.007043,0.030252,0.009670
8417,-0.002041,-0.016665,-0.003110,-0.022474,-0.000710,-0.022666,-0.004170,-0.007066,-0.011865,-0.011066,...,0.003116,0.041207,0.003964,-0.013548,-0.005989,-0.001077,-0.010831,-0.008989,0.007341,0.010897

# Apply static weight (relative) portfolio on every stock equally

In [31]:
import numpy as np
weights = np.ones(456) / 456
relative_portfolio = returns.dot(weights)
relative_portfolio

905    -0.005494
906    -0.000159
909     0.011286
910     0.005694
911    -0.000954
          ...
8413    0.002459
8414   -0.001991
8415    0.014854
8416    0.008599
8417   -0.006523
Length: 5179, dtype: float64

# Calculate mean return, volatility, variance, sharpe ratio, and VaR 95%

In [47]:
print("Mean Return (how much percentage did the portfolio gain per day on average):", relative_portfolio.mean())
print("Volatility (percentage that the portfolio fluctuates per day on average):", relative_portfolio.std())
print("Sharpe Ratio (return per unit of volatility):", relative_portfolio.mean()/relative_portfolio.std())
print("VaR 95% (maximum percentage of loss on 95% of days):", relative_portfolio.quantile(0.05))

Mean Return (how much percentage did the portfolio gain per day on average): 0.0006818827553907636
Volatility (percentage that the portfolio fluctuates per day on average): 0.012926980534213019
Sharpe Ratio (return per unit of volatility): 0.052748803449194324
VaR 95% (maximum percentage of loss on 95% of days): -0.018801094035494705